name: Deploy Website

on:
  push:
    branches:
      - task3-tharuntomy   # triggers when you push to main
      
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Upload files as artifact
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./   # deploy whole repo 

      # 3. Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
